version: '3.8'

services:
  ethereum-miner:
    image: ethereumminer/ethminer:latest
    container_name: ethereum-miner
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - POOL_ADDRESS=${POOL_ADDRESS}
      - PORT=${PORT}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
    command: >
      ethminer -P stratum+tcp://${POOL_ADDRESS}:${PORT} -U -O ${WALLET_ADDRESS}
    deploy:
      resources:
        limits:
          devices:
            - driver: nvidia
              capabilities: [gpu]
