services:
  nvidia-gpu-miner:
    image: xmrig/xmrig:latest
    container_name: nvidia-gpu-miner
    restart: always
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: >
      xmrig
      -a kawpow
      -o ${NVIDIA_POOL_ADDRESS}
      -u ${NVIDIA_WALLET_ADDRESS}
      -p x
      --cuda
      --no-cpu

  intel-gpu-miner:
    image: xmrig/xmrig:latest
    container_name: intel-gpu-miner
    restart: always
    devices:
      - /dev/dri:/dev/dri
    command: >
      xmrig
      -a kawpow
      -o ${INTEL_POOL_ADDRESS}
      -u ${INTEL_WALLET_ADDRESS}
      -p x
      --opencl
      --no-cpu

  cpu-miner:
    image: xmrig/xmrig:latest
    container_name: cpu-miner
    restart: no
    command: >
      xmrig -o ${CPU_POOL_ADDRESS} -u ${CPU_WALLET_ADDRESS} -p x --cpu-priority=3
