version: '3.8'

services:
  nvidia-gpu-miner:
    image: ethereumminer/ethminer:latest
    container_name: nvidia-gpu-miner
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_POOL_ADDRESS=${NVIDIA_POOL_ADDRESS}
      - NVIDIA_PORT=${NVIDIA_PORT}
      - NVIDIA_WALLET_ADDRESS=${NVIDIA_WALLET_ADDRESS}
    command: >
      ethminer -P stratum+tcp://${NVIDIA_POOL_ADDRESS}:${NVIDIA_PORT} -U -O ${NVIDIA_WALLET_ADDRESS}
    deploy:
      resources:
        limits:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  
  intel-gpu-miner:
    image: ethereumminer/ethminer:latest
    container_name: intel-gpu-miner
    restart: unless-stopped
    environment:
      - INTEL_POOL_ADDRESS=${INTEL_POOL_ADDRESS}
      - INTEL_PORT=${PORT}
      - INTEL_WALLET_ADDRESS=${INTEL_WALLET_ADDRESS}
    devices:
      - /dev/dri:/dev/dri
    command: >
      ethminer -P stratum+tcp://${INTEL_POOL_ADDRESS}:${PORT} -G -O ${INTEL_WALLET_ADDRESS} --opencl-device Intel

  cpu-miner:
    image: xmrig/xmrig:latest
    container_name: cpu-miner
    restart: unless-stopped
    environment:
      - CPU_POOL_ADDRESS=${CPU_POOL_ADDRESS}
      - CPU_WALLET_ADDRESS=${CPU_WALLET_ADDRESS}
    command: >
      xmrig -o ${CPU_POOL_ADDRESS} -u ${CPU_WALLET_ADDRESS} -p x --cpu-priority=3
