version: '3.8'

services:
  nvidia-gpu-miner:
    image: ethereumminer/ethminer:latest
    container_name: nvidia-gpu-miner
    restart: no
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: >
      ethminer -P stratum+tcp://${NVIDIA_POOL_ADDRESS} -U -O ${NVIDIA_WALLET_ADDRESS}
    deploy:
      resources:
        limits:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  
  intel-gpu-miner:
    image: ethereumminer/ethminer:latest
    container_name: intel-gpu-miner
    restart: no
    devices:
      - /dev/dri:/dev/dri
    command: >
      ethminer -P stratum+tcp://${INTEL_POOL_ADDRESS} -G -O ${INTEL_WALLET_ADDRESS} --opencl-device Intel

  cpu-miner:
    image: xmrig/xmrig:latest
    container_name: cpu-miner
    restart: no
    command: >
      xmrig -o ${CPU_POOL_ADDRESS} -u ${CPU_WALLET_ADDRESS} -p x --cpu-priority=3
